class_name MyEnums

# Track Enums
enum WEATHER_STATE {SUNNY, CLOUDY, RAIN, FOG, THUNDERSTORM}
enum RACE_STATE {GRIDWALK, STARTING, RACING, SAFETY_CAR, RED_FLAG, RACE_ENDED}

# Car Enums
enum CAR_STATE {ON_TRACK, RACE_START, PITTING, IN_BOX, MALFUNCTIONING, CRASHED}
enum DRIVING_STATE {ACCELERATING, BRAKING, IDLING, OFF}
enum DRIVER_STATE {HAPPY, FOCUSED, SCARED, CONFUSED, GRUMPY, ANGRY, TIRED, EXHAUSTED}

# Camera & Visual Enums
enum CAM_MOVE_STATE {DRAG, ZOOM, SCROLL}
enum FADE_STATE {IN, PAUSE, OUT}
